### ISSUE TITLE
Request for dataset.

### ISSUE THREAD

**Issue by harshitgrg** [AKSHAYSHARMAJS/Subjective-Answer-Evaluator#1]
Hello there, I was checking your source code about subjective answer evaluator, can you please help me configure it and provide with the dataset you have used.

**Comment by akshaysharmajs** [comment]
Hey @harshitgrg, I can't really share the dataset as I created it from the original answer sheets of my university which I got after a lot of effort (that is why I have not uploaded it and it is too large). I recommend you to do something similar, you just need student answers sheets and a marking scheme containing teacher's answers(the correct ones) to train the model. 

I also recommend you to use some good OCR like (Tesseract or Cloud Vision API) which are paid for scanning the text from the handwritten answer sheets. I used the Cloudmersive API which is free and good but not perfect. 

And you will need this file [https://www.kaggle.com/watts2/glove6b50dtxt](url) for the program to run.
